// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBExDxFP52s_m3BtWj8J_GIcr13YHB_3S4',
    appId: '1:938718442319:web:7e099776fb5612e8f0cb3a',
    messagingSenderId: '938718442319',
    projectId: 'ai-triad',
    authDomain: 'ai-triad.firebaseapp.com',
    storageBucket: 'ai-triad.appspot.com',
    measurementId: 'G-J7LDLYQJWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkYh45BeZdmLT4iSa6BPAANVAXEoTjxxA',
    appId: '1:938718442319:android:83a007afcf361385f0cb3a',
    messagingSenderId: '938718442319',
    projectId: 'ai-triad',
    storageBucket: 'ai-triad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB7_1XLF-JTfEL7-LjQoxr2Gfqqa_a8Qg',
    appId: '1:938718442319:ios:b495db6b34614513f0cb3a',
    messagingSenderId: '938718442319',
    projectId: 'ai-triad',
    storageBucket: 'ai-triad.appspot.com',
    iosClientId:
        '938718442319-qsh0dq0ipr4manlmjvlq46acjlqd3c1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.secretApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB7_1XLF-JTfEL7-LjQoxr2Gfqqa_a8Qg',
    appId: '1:938718442319:ios:b495db6b34614513f0cb3a',
    messagingSenderId: '938718442319',
    projectId: 'ai-triad',
    storageBucket: 'ai-triad.appspot.com',
    iosClientId:
        '938718442319-qsh0dq0ipr4manlmjvlq46acjlqd3c1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.secretApp',
  );
}
