// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3NltJlaUaGdHfEpJAUY6FxtXGDUktJPI',
    appId: '1:214754856600:web:bffd14430d15df973b0aed',
    messagingSenderId: '214754856600',
    projectId: 'doctor-robo',
    authDomain: 'doctor-robo.firebaseapp.com',
    databaseURL:
        'https://doctor-robo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doctor-robo.appspot.com',
    measurementId: 'G-S31M2K58B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhZxsFsu9dSYW7LvWiKIICN5q3hRVHVkw',
    appId: '1:214754856600:android:2042f526ac24b6453b0aed',
    messagingSenderId: '214754856600',
    projectId: 'doctor-robo',
    databaseURL:
        'https://doctor-robo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doctor-robo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuYwATCAXZKYa7h8Io0MuqbpxfI4xz2p0',
    appId: '1:214754856600:ios:7454331f903939983b0aed',
    messagingSenderId: '214754856600',
    projectId: 'doctor-robo',
    databaseURL:
        'https://doctor-robo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doctor-robo.appspot.com',
    iosClientId:
        '214754856600-b4rvqqrodejgu4g3iao10rfsra6cg2l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.secretApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuYwATCAXZKYa7h8Io0MuqbpxfI4xz2p0',
    appId: '1:214754856600:ios:7454331f903939983b0aed',
    messagingSenderId: '214754856600',
    projectId: 'doctor-robo',
    databaseURL:
        'https://doctor-robo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doctor-robo.appspot.com',
    iosClientId:
        '214754856600-b4rvqqrodejgu4g3iao10rfsra6cg2l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.secretApp',
  );
}
